"""Neroxia Database Package."""

from .connection import AsyncSessionLocal, engine, get_db
from .crud import (
    add_tag_to_user,
    cancel_user_pending_follow_ups,
    create_deal,
    create_follow_up,
    create_message,
    create_note,
    create_tag,
    create_user,
    delete_deal,
    delete_note,
    get_all_active_users,
    get_all_configs,
    get_all_deals,
    get_all_tags,
    get_config,
    get_crm_metrics,
    get_deal_by_id,
    get_pending_follow_ups,
    get_recent_messages,
    get_user_active_deal,
    get_user_by_id,
    get_user_by_phone,
    get_user_deals,
    get_user_follow_ups,
    get_user_messages,
    get_user_notes,
    get_user_tags,
    get_users_by_mode,
    init_default_configs,
    mark_deal_lost,
    mark_deal_won,
    remove_tag_from_user,
    set_config,
    sync_deal_stage_from_user,
    update_deal,
    update_follow_up_status,
    update_user,
)
from .models import Base, Config, Deal, FollowUp, Message, Note, Tag, User, UserTag
from .subscription_models import (
    BillingHistory,
    SubscriptionPlan,
    UserProfile,
    UserSubscription,
    UsageTracking,
)

__all__ = [
    # Connection
    "engine",
    "AsyncSessionLocal",
    "get_db",
    # Models
    "Base",
    "User",
    "Message",
    "FollowUp",
    "Config",
    "Deal",
    "Note",
    "Tag",
    "UserTag",
    # Subscription Models
    "BillingHistory",
    "SubscriptionPlan",
    "UserProfile",
    "UserSubscription",
    "UsageTracking",
    # CRUD - User operations
    "get_user_by_phone",
    "get_user_by_id",
    "create_user",
    "update_user",
    "get_all_active_users",
    "get_users_by_mode",
    # CRUD - Message operations
    "create_message",
    "get_user_messages",
    "get_recent_messages",
    # CRUD - Follow-up operations
    "create_follow_up",
    "get_pending_follow_ups",
    "get_user_follow_ups",
    "update_follow_up_status",
    "cancel_user_pending_follow_ups",
    # CRUD - Config operations
    "get_config",
    "set_config",
    "get_all_configs",
    "init_default_configs",
    # CRUD - CRM Operations
    "create_deal",
    "get_deal_by_id",
    "get_user_deals",
    "get_all_deals",
    "update_deal",
    "mark_deal_won",
    "mark_deal_lost",
    "delete_deal",
    "create_note",
    "get_user_notes",
    "delete_note",
    "create_tag",
    "get_all_tags",
    "add_tag_to_user",
    "remove_tag_from_user",
    "get_user_tags",
    "get_crm_metrics",
    "sync_deal_stage_from_user",
    "get_user_active_deal",
]
